# roles/rhbase/tasks/config.yml
---

# This speeds up the Gathering Facts phase and several other situations where
# a DNS lookup is performed on the host name.

- name: Config | Ensure host name is in the hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ ansible_host }} {{ ansible_hostname }}.{{ ansible_domain }} {{ ansible_hostname }}"
    regexp: "{{ ansible_hostname }}"
  when: rhbase_hosts_entry
  tags:
    - rhbase
    - config

- name: Config | Install custom `/etc/motd` file
  template:
    src: etc_motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  when: rhbase_motd == true
  tags:
    - rhbase
    - config

- name: Config | Set the TZ environment variable
  template:
    src: etc_profile.d_localtime.j2
    dest: /etc/profile.d/localtime.sh
  tags:
    - rhbase
    - config
