- name: Katello | Add local repository
  yum_repository:
    name: local-8
    description: Local EL 8 RPMs
    baseurl: "{{ rhbase_kt_localrepo }}"
    gpgcheck: no
  when: rhbase_kt_localrepo is defined  


- name: Katello | Clean yum/dnf cache
  command: yum clean all

- name: Katello | Remove RHN/Spacewalk/Oracle Linux Manager
  package:
    name: "{{ rhbase_rhn_packages }}"
    state: absent
  when: ansible_distribution == "OracleLinux"

- name: Katello | Checking subscription certificates
  package:
    name: subscription-manager
    state: present

- name: Katello | Install certificate package
  package:
    name: "{{ rhbase_kt_certs}}"
    state: present
    validate_certs: no
    disable_gpg_check: yes

- name: Katello | Register system to Katello
  redhat_subscription:
    state: present
    activationkey: "{{ rhbase_kt_activationkey }}"
    org_id: "{{ rhbase_kt_org_id }}"
  register: subscription 

- block: 
  - name: Katello | Remove default repositories
    yum_repository:
      name: "{{ item }}"
      file: "{{ rhbase_defaultrepofiles }}"
      state: absent
    with_items:
      - "{{ rhbase_defaultrepos }}"
       
  when: 
    - subscription["msg"] == "System successfully registered*" or "System already registered."
    - rhbase_defaultrepos is defined
  
- name: Katello | Run package updates
  package:
    name: '*'
    state: latest
  register: updated

- name: Katello | Reboot immediately if system was updated.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: updated.changed 

- name: Katello | Wait for the reboot to complete 
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: updated.changed
